DROP DATABASE IF EXISTS game;
CREATE DATABASE game;
USE game;
CREATE TABLE Game (
	GameID INTEGER PRIMARY KEY NOT NULL, 
	points INTEGER NOT NULL,
	fecha VARCHAR(50) NOT NULL,
	time VARCHAR(50),
	duration FLOAT,
	winner VARCHAR(50) NOT NULL
)ENGINE = InnoDB;

CREATE TABLE Player (
	username VARCHAR(50) PRIMARY KEY NOT NULL, 
	password VARCHAR(50) NOT NULL
)ENGINE = InnoDB;

CREATE TABLE Questions (
	questionID INTEGER PRIMARY KEY NOT NULL,
	question VARCHAR(50) NOT NULL
)ENGINE = InnoDB;

CREATE TABLE Answers (
	answerID INTEGER PRIMARY KEY NOT NULL,
	answer VARCHAR(50) NOT NULL
)ENGINE = InnoDB;

CREATE TABLE QuestionsRel (
	questID INTEGER,
	answID INTEGER NOT NULL,
	FOREIGN KEY (questID) REFERENCES Questions(questionID),
	FOREIGN KEY (answID) REFERENCES Answers(answerID)
)ENGINE = InnoDB;

CREATE TABLE Participation (
	Player VARCHAR(50) NOT NULL,
	Game INTEGER,
	FOREIGN KEY (Player) REFERENCES Player(username),
	FOREIGN KEY (Game) REFERENCES Game(GameID)
)ENGINE = InnoDB;

